### ISSUE TITLE
ERROR, Scans failed for VirtualMemoryFlag 

### ISSUE THREAD

**Issue by HugoBelin** [FrankvdStam/SoulSplitter#10]
![image](https://user-images.githubusercontent.com/128939485/227771535-51249663-c191-4a85-95fc-c77786c25551.png)
![image](https://user-images.githubusercontent.com/128939485/227771538-3dd415a2-ed3e-48d6-a84c-73c9afbe3152.png)
Hey I have this error message when i try to custom split Elden Ring. I think this is the cause of the time that doesn't start when i go for a new run in ER ( sry for my ban english )

**Comment by FrankvdStam** [comment]
What version of elden ring are you running? Do you have any mods installed?

**Comment by HugoBelin** [comment]
> What version of elden ring are you running? Do you have any mods installed?

I'm on the last version of Elden Ring with no mod installed 
idk how, but the timer started when i was speedrunning 2h ago, but there was no split. 
![image](https://user-images.githubusercontent.com/128939485/227784877-ad3b7d88-d1bd-4fad-b11b-79230f616984.png)

**Comment by FrankvdStam** [comment]
Looks like the timer itself is okay, blackscreen removal works as well, it's only the automatic splits that have an issue. I'll fix this eventually, I'd advise you for the time being to either split manually (it doesn't look like have any splits setup in your screenshot, [make sure to create them](https://www.speedgamingnews.com/how-to-set-up-livesplit-guide-with-screenshots/), soulsplitter doesn't create them for you) or to [downpatch](https://wiki.speedsouls.com/eldenring:Downpatching) to the previous version if you need working autosplits.

**Comment by HugoBelin** [comment]
> Looks like the timer itself is okay, blackscreen removal works as well, it's only the automatic splits that have an issue. I'll fix this eventually, I'd advise you for the time being to either split manually (it doesn't look like have any splits setup in your screenshot, [make sure to create them](https://www.speedgamingnews.com/how-to-set-up-livesplit-guide-with-screenshots/), soulsplitter doesn't create them for you) or to [downpatch](https://wiki.speedsouls.com/eldenring:Downpatching) to the previous version if you need working autosplits.

ok, i will looking for manual spliting, but maybe it could be my fault,

**Comment by FrankvdStam** [comment]
This has been fixed in 1.4.2
