### ISSUE TITLE
Activating SoulSplitter on Linux fails

### ISSUE THREAD

**Issue by luciferofastora** [FrankvdStam/SoulSplitter#26]
Use Context: Trying to get Livesplit + Auto Splitter to work on Linux. Tried on Dark Souls and Sekiro.

I've gotten Livesplit to start, ostensibly in the same Proton Compatibility runtime environment as the game. I can select the game, but trying to activate SoulSplitter produces an error message: 

> The Auto Splitter could not be activated. (Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.)

I've not found any info where logs might be found to figure out the source of this issue. Any troubleshooting ideas I could try to help?

**Comment by FrankvdStam** [comment]
Soulsplitter consist of multiple files, livesplit sometimes acquires the main file (soulsplitter.dll) but fails to download some of the others, causing this error. What you could try is deleting the main file (<livesplit install directory>/components/soulsplitter.dll) and then reactivating soulsplitter in livesplit, that will prompt livesplit to reacquire all files. 

If that doesn't solve the issue then I'll need the log. Normally on windows, the log is written to <my documents>/soulsplitter/soulsplitter.log. You could send that to me and then I can have a look at what is breaking.

Hope this helps, feel free to DM me on discord. https://discord.com/users/281116269921566721

**Comment by luciferofastora** [comment]
For anyone else stumbling across this: The heart of the issue is that SoulSplitter requires WPF, which the Mono Runtime, built into Proton to support most .NET applications, hasn't implemented at the time of this comment ([Source](https://www.mono-project.com/docs/about-mono/compatibility/)).  
The solution would involve using winetricks or protontricks to install a dotnet package, but I've not got that working so far. 

In any event, that's no longer in the scope of this issue or project, so as per our discord conversation, I'm closing it. Thanks for your help!
