### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by FrankvdStam** [FrankvdStam/SoulSplitter#4]
https://github.com/Haukinger/SoulSplitter
https://github.com/Haukinger/SoulSplitter/commit/693201b64a71b8171b205d520517f6e75301711a

Hi,

I'm hoping that by having the above URL's, you will be notified of this issue.

It's cool to see soulsplitter being used in other projects. Thats the reason why soulmemory is a separate project that can easily be used elsewhere. However, I have not worked on this long and hard for you to strip my name and copyright notice off.

I can see this happening by accident, during a conversion to the new .NET project format, though it is still a big neglect in my opinion. The new project format also supports author, license and copyright information via the <Authors> and <Copyright> tags respectively.

![image](https://user-images.githubusercontent.com/37239092/188700502-85320116-2e07-42eb-b0c3-193be74b9b99.png)

You also left no way to contact you. No issues, no email, no discord, which is making me jump through hoops to get this information across. 

I'll wait a couple days and hope you see this, since it can be easily resolved by retaining my copyright notice. If not, I'll have to report this over at gnu.org.

**Comment by Haukinger** [comment]
... going to rectify this ... not intentional at all

**Comment by Haukinger** [comment]
copyright notice restored, see https://github.com/FrankvdStam/SoulSplitter/commit/fb9b0db6bbc814b719a7aaeffd13e2d6848f4631

**Comment by FrankvdStam** [comment]
I welcome the fork, it was always my intention to put SoulMemory up on nuget. But I do want to get credit for my work. Thanks for fixing this :)
