### ISSUE TITLE
Scans Failed for VirtualMemoryFlag

### ISSUE THREAD

**Issue by ZenoNox** [FrankvdStam/SoulSplitter#43]
I have been trying to use the autosplitter to run splits for ER but I keep getting an error that says 'Scans Failed for VirtualMemoryFlag' and Im not quite sure what to do about it.

Any thoughts would be helpful.  

Thanks

**Comment by FrankvdStam** [comment]
ER 1.12 broke the timer. I sent a fix for the timer to the ER mod-team. Normally I will just fix things, but the timer is a little more sensitive, so I want to have it verified first. I am leaving this scan error there on purpose to prevent people from submitting runs with an invalid timer. Just be a little more patient for the mod team to finish testing and then I will push an update.

**Comment by ZenoNox** [comment]
Oh ok. I was just unsure about why it was busted. Makes sense though. Thank you

**Comment by soarqin** [comment]
https://github.com/soarqin/SoulSplitter/commit/d1a742fff8fca99893d915c3e5c291675fb6c937
I have a temp fix that use remote mem allocation for hooking, which works fine for 1.12.x

PS: the new 1.12 support rewritten by @FrankvdStam with rust has an issue that if you restart LiveSplit without closing Elden Ring, the injection DLL is using by game can not be overwritten and an error dialog will popup.

**Comment by FrankvdStam** [comment]
@soarqin this error is handled on my branch afaik https://github.com/FrankvdStam/SoulSplitter/blob/283cec90212d68ff0d9922783916cf6e8088f780/src/SoulMemory/soulmods/Soulmods.cs#L142
maybe its bugged.

**Comment by soarqin** [comment]
> @soarqin this error is handled on my branch afaik
> 
> https://github.com/FrankvdStam/SoulSplitter/blob/283cec90212d68ff0d9922783916cf6e8088f780/src/SoulMemory/soulmods/Soulmods.cs#L142
> 
> 
> maybe its bugged.

I'd think if the dll is not changed, this dialog(or even the overwriting) is not needed at all.

**Comment by FrankvdStam** [comment]
Always overwriting saves you the effort of coding that logic. Regardless of any of this, the mod team still didn't get back to me so as of now, there is still no official way to support MIGT for ER1.12.

**Comment by FrankvdStam** [comment]
This is now fixed in 1.7.0.
