### ISSUE TITLE
Trigger Position Dont Work on last Version of Elden ring

### ISSUE THREAD

**Issue by neimex23** [FrankvdStam/SoulSplitter#5]
I send this issue case for tell you that position on Elden Ring dont work in the last version.
Kill boss, active grace and custom flag look work fine but this not

**Comment by FrankvdStam** [comment]
Fix will be out soon, testing some other changes before releasing.

**Comment by FrankvdStam** [comment]
Fixed now in 1.1.6

**Comment by FrankvdStam** [comment]
@neimex23 SoulMemory is now targeting .net standard 2.0 and is distributed via nuget https://www.nuget.org/packages/SoulMemory

**Comment by neimex23** [comment]
amazing im added into my project, excelent work
