### ISSUE TITLE
Inventory indices get reset regardless of the settings

### ISSUE THREAD

**Issue by AndrovT** [FrankvdStam/SoulSplitter#6]
**Steps to reproduce:**
- Uncheck "Reset inventory indices" in Dark Souls 1 settings
- Equip and unequip something that's not at the top of the list
- Start and reset splits
- Try to equip something in the same slot as before, it now defaults to the top on the list

**Expected behavior:**

Only reset indices when checkbox is checked

**Comment by FrankvdStam** [comment]
Thanks for letting me know, am unfortunately not able to reproduce. 
It is being checked for here:
https://github.com/FrankvdStam/SoulSplitter/blob/8a6451491a820fc6eb30f5c664d72ea39656bf07/src/SoulSplitter/Splitters/DarkSouls1Splitter.cs#L111

Are you sure this is actually soulsplitter causing a reset?
I did notice some people had Capitaine's timer added to their livesplit layout, which also can reset the indices. Can you check to make sure you only have 1 timer active?
![image](https://user-images.githubusercontent.com/37239092/202444041-b33f70df-9ef4-4c43-9528-a8e057a2dacf.png)

**Comment by FrankvdStam** [comment]
@AndrovT?
