### ISSUE TITLE
Can you please help make a timer splitter

### ISSUE THREAD

**Issue by PzcNtyz** [FrankvdStam/SoulSplitter#67]
Can you make a timer splitter for Black Myth Goku, I want each boss to be divided, and there are only chapters at the moment. You can get paid, thank you

**Comment by FrankvdStam** [comment]
Do you mean black myth wukong?

**Comment by PzcNtyz** [comment]
> 你是说黑神话悟空吗？

是的，因为目前只有章节自动分割，想要一个BOSS自动分割，每次切换分割还要手动，比较麻烦
Yes, because there is only automatic division of chapters at present, and if you want a BOSS to be automatically divided, you have to manually switch the division every time, which is more troublesome

**Comment by PzcNtyz** [comment]
如果您可以制作的话，我可以把目前需要制作的boss节点，发送给您
If you can make it, I can send you the boss nodes that need to be crafted at the moment

**Comment by FrankvdStam** [comment]
https://github.com/TheDementedSalad/Black-Myth-Wukong-Autosplitter
Did you reach out to TheDementedSalad?

**Comment by FrankvdStam** [comment]
Alright, thanks for reaching out to me, I do like wukong, but making timers/autosplitters the way I've done it in soulsplitter can take hundreds of hours. I really don't have that kind of time on my hands right now. Maybe someday in the future.
