### ISSUE TITLE
The Auto Splitter could not be activated

### ISSUE THREAD

**Issue by BaptisteBurguiere** [FrankvdStam/SoulSplitter#69]
Hello,

I've been using the soul splitter for several days now without any issue. But today, after launching livesplit I am having this error (sorry the message is in french):
![image](https://github.com/user-attachments/assets/bc8948fa-bc3b-4b74-9b0e-8806c4f4825c)
When I try to activate soul splitter in the edit splits menu, I am having this error:
![image](https://github.com/user-attachments/assets/646fe1e0-a6d9-45e2-8f1e-3a71221f1a8c)
The issue is not coming from windows defender (I already have allowed the files and I don't have any notification from windows defender) and I tried to manually install the files here but nothing changes:
![image](https://github.com/user-attachments/assets/150c4f40-ba4a-4539-ac5c-9ebd1fbe22f2)

Thank you for your help!

**Comment by FrankvdStam** [comment]
Maybe this page can help: https://soulsspeedruns.com/livesplit/#troubleshooting

Soulinjectee.dll is very old, you no longer need it and can safely delete it. The files you need are:
- SoulSplitter.dll
- SoulMemory.dll
- MaterialDesignThemes.Wpf.dll
- MaterialDesignColors.dll

If you still have trouble after trying all this, send me a DM on discord

**Comment by BaptisteBurguiere** [comment]
Yeah, I've already used this link.
Well I've litterally done nothing since yesterday and now it's working properly. I don't know why but I won't complain.
Thank you for you help and sorry for bothering you!

**Comment by FrankvdStam** [comment]
No worries, glad its working.
