### ISSUE TITLE
Suggestion of NG+ in SoulsGames

### ISSUE THREAD

**Issue by neimex23** [FrankvdStam/SoulSplitter#7]
Hey im ask if any possible to add into SoulsMemory.dll a function for all games that return boolean if is a NG+ is started, and reset flags in the memory?, ex in sekiro if a ng+ is started the flags of previous runs still up, preventing being able to pass repeated splits after a run in ng+ even if restart a run.
Maybe is not possible i thing that is a problem of how the game was developed but for my project is more common see multiples runs in ng+

thx for your time
regards.

**Comment by FrankvdStam** [comment]
Are you talking about event flags? The game resets them automatically when you go into a new game cycle. 

Dark souls 1 has `int NgCount();` to obtain the current NG cycle. Can add something similar for the other souls games.

**Comment by neimex23** [comment]
Yes, I'm talking about the event flag and it is my bad. I checked the wrong flag between ng.
But I appreciate a function like ds1 because I set a true internal var when an event happens to avoid autosplit forever and this var only is changed backward if the user reset the run. With the ng function i can develop that if NG is different to current ng reset the splits var

**Comment by FrankvdStam** [comment]
I've decided I'm not going to help you going forward.

- You don't credit me or my work at all
- I see a kofi link, asking for money for the work of others?
- My work is GPLv3 licensed, while your is MIT. That's not legal

**Comment by neimex23** [comment]
I don't believe this. I want to ask apologize if I disrespect you at any time.

I'm tell everytime if tell me what my addons work that check a flag with your dll, I'm added you into the program,licence party file, a specific file for you I don't know what do you need more, I'm going to add you into readme tomorrow ,
Add a link to your repo if SoulsMemory is update too.

The people, don't have the obligations to donate to me if the people give me any is for about 30k lines of I do to make compatible HitCounterManager to your dll and other splitters of livesplit your code can't be seen anywhere only the public's functions of your dll or something struct similar about numbers of flags or whatever.
To avoid more conflict with this I remove links to donations in fact from I added donations so far I don't earn anything, can I send you the analytics of ki-fi and PayPal if you want.

NoHit is a small community comparing to SpeedRunners so..

I want to stay on good terms because I want to be able to continue using SoulsMemory.dll to maintain this, I am unable to recreate something as good as that, sorry if you thought I was taking advantage of your work.

All good if you want not to help me anymore, but don't throw my work down.

Merry Christmas
Regards
