### ISSUE TITLE
DSR Downpatching issues

### ISSUE THREAD

**Issue by egor-poryadin** [FrankvdStam/SoulSplitter#71]
Hello :)
After downpatching Dark Souls Remastered to 1.01, LiveSplit only shows the game time [from the first save slot during quitouts](https://www.youtube.com/watch?v=CL58DWschsA), as well as constantly spamming errors in the log (could be unrelated): 
![image](https://github.com/user-attachments/assets/31cf4f48-7911-42e8-88f1-85a6d54a412f)
Thanks in advance for you help

**Comment by FrankvdStam** [comment]
Thanks for reporting this, will look into it.

**Comment by FrankvdStam** [comment]
Fix https://github.com/FrankvdStam/SoulSplitter/pull/72

**Comment by FrankvdStam** [comment]
The fix has been merged but not release. The first next update will contain the fix, until then you can keep using the manually installed version.
